services:
  - name: laravel-app
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DATABASE_URL
        fromDatabase:
          name: sendnotes
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_URL
        value: https://sendnotes-kb17.onrender.com
