services:
  - name: laravel-app
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DATABASE_URL
        fromDatabase:
          name: sendnotes
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_URL
        value: https://sendnotes-kb17.onrender.com
  - type: web
    name: my-app
    env: php
    buildCommand: |
      apt-get update && apt-get install -y php8.3-cli
      composer install --optimize-autoloader --no-dev
